### ISSUE TITLE
I can´t run npm test or npm start

### ISSUE THREAD

**Issue by kfern** [bigtestjs/examples#4]
Hi! 

I can´t run npm test or npm start. Fresh install.  Node v8.11.1 in Windows 7

> PS D:\examples\react\countdown> npm test

countdown@1.0.0 test D:\examples\react\countdown
bigtest run

D:\examples\react\countdown\node_modules\yargs\yargs.js:1144
      else throw err
           ^
```

TypeError: Cannot read property 'toString' of null
    at getDefaultBrowser (D:\examples\react\countdown\node_modules\@bigtest\cli\dist\run\util\browser.js:19:76)
    at BrowserManager.assign.browsers.browsers.map.browser (D:\wamp\www\dred-nhd-2k18\dred-tareas\examples\react\countdown\node_modules\@bigtest\cli\dist\run\browsers\index.js:63:52)
    at Array.map (<anonymous>)
    at new BrowserManager (D:\examples\react\countdown\node_modules\@bigtest\cli\dist\run\browsers\index.js:61:26)
    at new Coordinator (D:\examples\react\countdown\node_modules\@bigtest\cli\dist\run\coordinator.js:63:20)
    at Object.handler (D:\examples\react\countdown\node_modules\@bigtest\cli\dist\run\index.js:128:11)
    at Object.runCommand (D:\examples\react\countdown\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (D:\examples\react\countdown\node_modules\yargs\yargs.js:1059:30)
    at Object.parse (D:\examples\react\countdown\node_modules\yargs\yargs.js:538:19)
    at Object.<anonymous> (D:\examples\react\countdown\node_modules\@bigtest\cli\dist\index.js:24:22)
```
npm ERR! Test failed.  See above for more details.

> PS D:\examples\react\countdown> npm start

ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] D:\examples\react\countdown\src\index.js:
As of v7.0.0-beta.55, we've removed Babel's Stage presets.
Please consider reading our blog post on this decision at https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets for more details. TL;DR is that it's more beneficial in the long run to explicitly add which proposals to use.

For a more automatic migration, we have updated babel-upgrade, https://github.com/babel/babel-upgrade to do this for you with "npx babel-upgrade".

If you want the same configuration as before:
```

{
  "plugins": [
    // Stage 2
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",

    // Stage 3
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    ["@babel/plugin-proposal-class-properties", { "loose": false }],
    "@babel/plugin-proposal-json-strings"
  ]
}

```
If you're using the same configuration across many separate projects, keep in mind that you can also create your own custom presets with whichever plugins and presets you're looking to use.

```
module.exports = function() {
  return {
    plugins: [
      require("@babel/plugin-syntax-dynamic-import"),
      [require("@babel/plugin-proposal-decorators"), { "legacy": true }],
      [require("@babel/plugin-proposal-class-properties"), { "loose": false }],
    ],
    presets: [
      // 
    ],
  };
};

```

Thanks in advance

**Comment by wwilsman** [comment]
Hey! Thanks for the issue!

We recently updated the example to use the BigTest CLI which is still in _very_ early development. What you're seeing seems to be an issue with how it detects the default browser. I've seen issues with this as well, so it's very likely to change next time I get around to working on the CLI.

We also just recently rolled back those changes to the example and split off a `countdown-karma` example that _does not_ use the BigTest CLI. Feel free to try out that example.

Since this issue is a problem with the BigTest CLI, I'm going to close it here and open a new issue over on that repo.
